### ISSUE TITLE
12장 담당하고 싶지 않아요.

### ISSUE THREAD

**Issue by choisuhyeok1255** [undefined-study/clean-code#83]
## 어떤 소단원을 담당하고 싶으신가요?
아직 고민중이에요

## 기타 공유해 주실 사항이 있나요?
없어요

**Comment by ahnanne** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ수혁님 어그로 뭐냐구요~~~
